# Generated by Django 5.0.3 on 2024-03-28 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('medicine_name', models.CharField(max_length=255)),
                ('medicine_des', models.CharField(max_length=500)),
            ],
        ),
    ]
