# Generated by Django 5.0.3 on 2024-03-31 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='records',
            name='creation_date',
        ),
    ]
